name: Update data (dry run)

on: workflow_dispatch

jobs:
  run_processing:
    # Is not allowed to run on GitHub-hosted runners because of the track data which needs to stay on TU Dresden servers.
    runs-on: self-hosted
    container: ubuntu:22.04
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --root-user-action=ignore

      - name: run script
        env:
          TRACKING_SERVICE_API_KEY: ${{ github.ref == 'refs/heads/main' && secrets.TRACKING_SERVICE_API_KEY_STAGING || github.ref == 'refs/heads/stable' && secrets.TRACKING_SERVICE_API_KEY_PRODUCTION || github.ref == 'refs/heads/release' && secrets.TRACKING_SERVICE_API_KEY_RELEASE }}
          TRACKING_SERVICE_URL: ${{ github.ref == 'refs/heads/main' && secrets.TRACKING_SERVICE_URL_STAGING || github.ref == 'refs/heads/stable' && secrets.TRACKING_SERVICE_URL_PRODUCTION || github.ref == 'refs/heads/release' && secrets.TRACKING_SERVICE_URL_RELEASE }}
          GRAPHHOPPER_SERVICE_URL: ${{ github.ref == 'refs/heads/main' && secrets.GRAPHHOPPER_SERVICE_URL_STAGING || github.ref == 'refs/heads/stable' && secrets.GRAPHHOPPER_SERVICE_URL_PRODUCTION || github.ref == 'refs/heads/release' && secrets.GRAPHHOPPER_SERVICE_URL_RELEASE }}
        run: | 
          python process.py --output False --debug False